version: '3'

services:
  db:
    image: postgres:9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - /home/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
